# Generated by Django 5.2.7 on 2025-12-03 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informacion', '0002_remove_tipocuenta_tipocuenta_id_tipocuenta_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagoservicio',
            name='monto',
        ),
        migrations.AddField(
            model_name='pagoservicio',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
