# Generated by Django 5.2.7 on 2025-12-03 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informacion', '0003_remove_pagoservicio_monto_pagoservicio_saldo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagoservicio',
            name='saldo',
        ),
        migrations.AddField(
            model_name='servicio',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
